apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-deploy
  namespace: proyecto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server-container
        image: us.gcr.io/usac-298718/grpc-server
        ports:
        - containerPort: 50051