 
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
  namespace: proyecto2
spec:
  selector:
    app: grpc-server
  ports:
    - port: 50051
      targetPort: 50051
  type: LoadBalancer