apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic
  namespace: proyecto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic
  template:
    metadata:
      labels:
        app: traffic
    spec:
      containers:
      - name: traffic
        image: us.gcr.io/usac-298718/traffic
        ports:
        - containerPort: 8080