apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-deploy
  namespace: proyecto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
      - name: dummy-container
        image: us.gcr.io/usac-298718/dummy
        ports:
        - containerPort: 80