apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-deploy
  namespace: proyecto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
      - name: grpc-client-container
        image: us.gcr.io/usac-298718/grpc-client
        ports:
        - containerPort: 4000