 
apiVersion: v1
kind: Service
metadata:
  name: grpc-client-service
  namespace: proyecto2
spec:
  selector:
    app: grpc-client
  ports:
    - port: 4000
      targetPort: 4000
  type: LoadBalancer